apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "my-antdpro.fullname" . }}
  labels:
    app: {{ template "my-antdpro.name" . }}
    chart: {{ template "my-antdpro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "my-antdpro.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "my-antdpro.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 10 }}
{{- end }}
{{- if .Values.extraEnv }}
          env:
{{ toYaml .Values.extraEnv | indent 10 }}
{{- end }}
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
        #   livenessProbe:
        #     httpGet:
        #       path: /health
        #       port: {{ .Values.service.port }}
        #   readinessProbe:
        #     httpGet:
        #       path: /health
        #       port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
